feat: cli tool register install
podman-desktop/podman-desktop-extension-minikube pull request #201
Opened 2024-11-04 15:56 UTC by axel7083

## Screenshots

1. minikube not installed

![image](https://github.com/user-attachments/assets/fcc7c41e-2a05-4e60-978e-c703a3c31499)

3. minikube installed

![image](https://github.com/user-attachments/assets/d9a31dda-fab5-4a89-84bf-4d9a89d50d47)

5. minikube update available

![image](https://github.com/user-attachments/assets/ef2da30d-e3fe-4b90-b2f2-3a81a2274d84)

## Related issues

Fixes https://github.com/containers/podman-desktop-extension-minikube/issues/149

## Testing

- [x] unit tests has been provided

1. go to CLITool
2. assert minikube cli tool card is visible
3. uninstall if already installed
4. assert no minikube provider in the resource page
5. install through cli tool page minikube
6. assert minikube provider in resource page

2024-11-05 06:19 UTC, gastoner commented
`pnpm format:fix` ?

2024-11-05 07:23 UTC, jeffmaury requested changes
Format seems invalid

Also but maybe not related to this PR, I found this strange that the tooltip are different on the Update button on the left and the Update link on the rigth

2024-11-05 10:13 UTC, axel7083 commented
> `pnpm format:fix` ? 

@gastoner My bad! Missed it :)

> Also but maybe not related to this PR, I found this strange that the tooltip are different on the Update button on the left and the Update link on the rigth

@jeffmaury The minikube cannot change the UI, therefore I would argue the problem is on the podman-desktop side 🤔 .

2024-11-05 11:11 UTC, gastoner reviewed
Works well, but when you try to install -> update -> uninstall -> install aggain -> you wont see update button (assuming you have instaled !latest version)

Linux WSL


https://github.com/user-attachments/assets/4864eed7-f034-4a37-bbb5-070a2c721390

2024-11-06 07:42 UTC, jeffmaury approved these changes
LGTM

2024-11-06 14:48 UTC, axel7083 commented
@gastoner I updated the code, the problem was I wasn't checking for update after the install, only in the activate. Should be fixed now, thanks for the catch 👍

2024-11-07 15:50 UTC, axel7083 commented
@gastoner the issue you encountered is related to https://github.com/containers/podman-desktop/pull/9813

2024-11-07 16:00 UTC, gastoner approved these changes

2024-11-07 17:17 UTC, merged